pipeline_class: "ExperimentPipelineForClassifier"
experiment_metadata:
  description: "Train classifier on top of BERT"
  tag: "bert"
logdir: "runs/"
load_disk_data:
tokenizer: "resources/emilyalsentzer_Bio_ClinicalBERT_tokenizer"
max_length: 512
train: True
evaluate: True
save_disk_data: False
from_pretrained: "emilyalsentzer/Bio_ClinicalBERT"
save_pretrained: False
load_from_checkpoint:
fit_modules_from: -1
fit_modules: # not implemented
learning_rate: 0.0001
lr_scheduler_type: 'linear'
warmup_ratio: 0.05
batch_size: 16
num_epochs: 1
evaluation_strategy: "epoch"
eval_steps:
log_steps: 1
save_strategy: "no"
save_total_limit: 1
save_steps:
downsample_train: 128
downsample_valid: 128
downsample_test: 128