pipeline_class: "ExperimentPipelineForClassification" # choose the pipeline
experiment_metadata:
  description: "ResNet based 1-D conv model for classification"
  tag: "exp_01_task2_cnn_res"
dataloader_util_class_name: "ProcessedTextDataLoaderUtil" # This utility class
# is supposed to return loaders upon invoking its `get_data_loaders`
dataloader_root_dir: "resources/processed_data_mini" # set root dir to load data from
shuffle: true
model_class_name: "CnnWithResidualConnection" # The network to use
load_from_checkpoint: false
checkpoint_path: ""
embedding_model_path: "resources/saved_models/embedding.model" #to load 
# word embeddings / vocabulary etc.
# NOTE: vaocalubalry file name is inferred from the model file name
cost_function_class_name: "CrossEntropyLoss"
threshold: 0.5
trainer_class_name: "NetworkTrainer"
num_epochs: 300
batch_size: 8
optimizer_class_name: "AdamW"
learning_rate: 0.001
scheduler: null
weight_decay: 0.0000001
logdir: "runs"
batch_log_frequency: 1 # Print log after after these many batches
tensorboard_log_frequency: 1 # Log scalars after these many batches
model_save_frequency: 2 # frequency in epochs
model_name_tag: "exp_01_task2_cnn_res" # it will be included in the model file name
do_class_weighting: null
class_weighting_scheme: null